### ISSUE TITLE
Add emerald Colors

### ISSUE THREAD

**Issue by renanrbs** [stone-payments/emerald-components-android#25]
The colors should be referenced as emerald colors

The colors were defined as the following
![image](https://user-images.githubusercontent.com/12678243/45774350-152dcb00-bc23-11e8-8f47-8372b291864d.png)

The colors should be a public resource

**Comment by Ekt0s** [comment]
Hi @renanrbs 
What do you need exactly ?

**Comment by renanrbs** [comment]
Hi @Ekt0s we need a public colors resource using the colors defined on the image with "emerald" prefix I.E emerald_primary, emerald_black_2, etc 

ref: https://developer.android.com/studio/projects/android-library#PrivateResources

**Comment by Ekt0s** [comment]
Okay, I'm taking care of it 👍
