### ISSUE TITLE
NumberFormatException For input string: "٠٠٠" on CurrencyTextWatcher

### ISSUE THREAD

**Issue by renanrbs** [stone-payments/emerald-components-android#95]
**Describe the bug**
NumberFormatException caused by CurrencyTextWatcher
[Logs](https://console.firebase.google.com/u/0/project/portal-3d8e1/crashlytics/app/android:com.portal.android/issues/5bbe66d7f8b88c2963607629?time=last-seven-days&sessionId=5CEE0D2900F000011C9C6B7EC6F05D54_DNE_0_v2)

**To Reproduce**
Could'nt reproduce, only firebase logs are available

**Expected behavior**
Show currency without crashing

**Comment by diegolucasb** [comment]
Please add firebase log here as evidence
